# Introduction to NumPy

**NumPy** (short for *Numerical Python*) is an open-source Python library widely used for numerical computations, data analysis, and scientific computing. It provides a powerful array object called the `ndarray`, which is much more efficient, flexible, and faster than Python’s built-in lists for numerical operations.

NumPy underlies almost the entire ecosystem of data science, machine learning, and deep learning in Python. Libraries like **Pandas**, **Matplotlib**, **SciPy**, **scikit-learn**, and **TensorFlow** all build upon NumPy arrays. Therefore, understanding NumPy is a foundational skill for working in data science and related fields.

## Key Features of NumPy:

- **ndarray**: A powerful N-dimensional array object optimized for numerical operations.
- **Vectorization**: Perform arithmetic operations element-wise without explicit Python loops, resulting in cleaner and more efficient code.
- **Broadcasting**: Automatically handle operations between arrays of different shapes.
- **Rich Linear Algebra Support**: Functions for matrix multiplication, decomposition, and more.
- **Interoperability**: Easily integrate with other libraries in the Python data ecosystem.

---

## Advantages of NumPy Over Python’s Built-in Lists

1. **Performance**:  
   NumPy arrays are stored in contiguous memory blocks, allowing for efficient looping at the C level. As a result, operations on NumPy arrays can be significantly faster (often by orders of magnitude) compared to equivalent operations on Python lists.

2. **Memory Efficiency**:  
   NumPy arrays require less memory than Python lists. They store data as fixed-type elements, making them more memory-efficient and allowing faster access to elements.

3. **Vectorization**:  
   Operations on NumPy arrays are vectorized, meaning arithmetic can be applied directly to arrays rather than element-by-element manually. This leads to shorter, cleaner code and often large performance gains.

4. **Convenient Math Functions and Tools**:  
   NumPy comes with a vast set of mathematical functions optimized for array operations. This simplifies many numerical tasks, from basic arithmetic to complex linear algebra.

---

In [ ]:
import numpy as np
import time
import sys

# Define a decorator to measure the execution time
def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()  # Record start time
        result = func(*args, **kwargs)
        end_time = time.time()  # Record end time
        execution_time = end_time - start_time
        print(f"{func.__name__} took {execution_time:.6f} seconds")
        return execution_time  # Return the execution time for comparison
    return wrapper

# --- Speed and Memory Efficiency Comparison --- #

# Function to add elements in a Python list
@timer
def add_python_list(py_list1, py_list2):
    return [a + b for a, b in zip(py_list1, py_list2)]

# Function to add elements in a NumPy array
@timer
def add_numpy_array(np_array1, np_array2):
    return np_array1 + np_array2

# Create two arrays (Python list and NumPy array) with 1 million elements
size = 1000000
py_list1 = list(range(size))
py_list2 = list(range(size))
np_array1 = np.array(range(size))
np_array2 = np.array(range(size))

# --- 1. Speed Comparison --- #
py_list_time = add_python_list(py_list1, py_list2)  # Time for Python list addition
np_array_time = add_numpy_array(np_array1, np_array2)  # Time for NumPy array addition

# Calculate the percentage speed improvement
speed_improvement = ((py_list_time - np_array_time) / py_list_time) * 100

# Display percentage speed improvement
print(f"\nPercentage speed improvement using NumPy: {speed_improvement:.2f}%")

# --- 2. Memory Efficiency Comparison --- #
py_list1_memory = sys.getsizeof(py_list1)  # Memory used by Python list
py_list2_memory = sys.getsizeof(py_list2)  # Memory used by Python list
np_array1_memory = np_array1.nbytes  # Memory used by NumPy array
np_array2_memory = np_array2.nbytes  # Memory used by NumPy array

# Display Types and Memory
print("\nType and Memory Efficiency Comparison:")
print(f"\nPython List type: {type(py_list1)}")
print(f"NumPy Array type: {type(np_array1)}")

print(f"\nPython List memory usage (per list): {py_list1_memory / (1024 ** 2):.2f} MB")
print(f"NumPy Array memory usage (per array): {np_array1_memory / (1024 ** 2):.2f} MB")


## Getting Started

### Installation

If you haven't installed NumPy yet, you can do so using `pip`:

```bash
    pip install numpy
```

Or with `conda` if you’re using Anaconda:

```bash
    conda install numpy
```

### Importing NumPy

The common convention is to import NumPy as `np`:


In [ ]:
import numpy as np

## NumPy Data Types (dtypes)

NumPy arrays are homogenous: all elements have the same data type. Some common NumPy data types include:

- `int8`, `int16`, `int32`, `int64`: Signed integers of various bit widths
- `uint8`, `uint16`, `uint32`, `uint64`: Unsigned integers
- `float16`, `float32`, `float64` (commonly just `float`): Floating-point numbers with different precisions
- `complex64`, `complex128`: Complex numbers
- `bool`: Boolean values (`True`/`False`)

When you create a NumPy array, NumPy will infer the data type from the data provided. You can also explicitly specify a dtype:


In [ ]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.dtype)  # float64


To view or change the dtype of an existing array:

In [ ]:
print(arr.dtype)               # Check current dtype
arr_int = arr.astype(np.int32) # Convert to int32

## Creating NumPy Arrays

There are several ways to create NumPy arrays:

1. **From Python Lists**:


In [5]:
arr = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])


2. **Using Built-in Array Creation Functions**:
   - `np.zeros(shape)`: Create an array filled with zeros
   - `np.ones(shape)`: Create an array filled with ones
   - `np.full(shape, fill_value)`: Create an array filled with a specified value
   - `np.eye(n)`: Create an identity matrix of size `n x n`
   - `np.arange(start, stop, step)`: Similar to Python’s `range`, create a range of values
   - `np.linspace(start, stop, num)`: Create `num` points spaced evenly between `start` and `stop`

   Examples:

In [ ]:
import numpy as np

# 1. np.zeros(shape): Create an array filled with zeros
zeros_arr = np.zeros((3, 4))  # 3x4 matrix of zeros
print("Array of Zeros:\n", zeros_arr)

# 2. np.ones(shape): Create an array filled with ones
ones_arr = np.ones((2, 5))  # 2x5 matrix of ones
print("\nArray of Ones:\n", ones_arr)

# 3. np.full(shape, fill_value): Create an array filled with a specified value
full_arr = np.full((2, 3), 7)  # 2x3 matrix filled with 7
print("\nArray filled with 7:\n", full_arr)

# 4. np.eye(n): Create an identity matrix of size n x n
identity_matrix = np.eye(4)  # 4x4 identity matrix
print("\nIdentity Matrix (4x4):\n", identity_matrix)

# 5. np.arange(start, stop, step): Similar to Python’s range, create a range of values
range_arr = np.arange(0, 10, 2)  # Values from 0 to 10, with a step of 2
print("\nRange Array (0 to 10, step 2):\n", range_arr)

# 6. np.linspace(start, stop, num): Create 'num' points spaced evenly between start and stop
linspace_arr = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("\nLinspace Array (5 values between 0 and 1):\n", linspace_arr)


3. **Random Arrays**:

In [ ]:
import numpy as np

# Generating random arrays
rand_arr = np.random.rand(3, 2)  # Uniformly distributed between 0 and 1
randn_arr = np.random.randn(3, 3)  # Normally distributed
rand_int = np.random.randint(10, 20, size=(3, 2))  # 3x2 matrix of integers between 10 and 19

# Display the arrays with messages
print("Randomly generated array with uniform distribution (between 0 and 1):")
print(rand_arr)
print('\n' + "-" * 100)

print("\nRandomly generated array with normal distribution (mean=0, std=1):")
print(randn_arr)
print('\n' + "-" * 100)

print("\nRandomly generated array with integers between 10 and 19:")
print(rand_int)


## NumPy Operators

NumPy supports a variety of operators that work element-wise on arrays:

### **Arithmetic Operators**:
- **`+`**: Addition
- **`-`**: Subtraction
- **`*`**: Multiplication
- **`/`**: Division
- **`**`**: Exponentiation
- **`%`**: Modulus

### Explanation of Each Operator:

1. **Addition (`+`)**:
   - Adds corresponding elements of `arr1` and `arr2`.
   - **Example**:
     ```python
     arr1 + arr2
     ```

2. **Subtraction (`-`)**:
   - Subtracts elements of `arr2` from `arr1`.
   - **Example**:
     ```python
     arr1 - arr2
     ```

3. **Multiplication (`*`)**:
   - Multiplies corresponding elements of `arr1` and `arr2`.
   - **Example**:
     ```python
     arr1 * arr2
     ```

4. **Division (`/`)**:
   - Divides elements of `arr1` by elements of `arr2`.
   - **Example**:
     ```python
     arr1 / arr2
     ```

5. **Exponentiation (`**`)**:
   - Raises each element of `arr1` to the power of the corresponding element in `arr2`.
   - **Example**:
     ```python
     arr1 ** arr2
     ```

6. **Modulus (`%`)**:
   - Returns the remainder of division of elements from `arr1` by corresponding elements from `arr2`.
   - **Example**:
     ```python
     arr1 % arr2
     ```

Example:

In [ ]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# 1. Addition (+)
addition_result = arr1 + arr2
print("Addition (arr1 + arr2):", addition_result)

# 2. Subtraction (-)
subtraction_result = arr1 - arr2
print("Subtraction (arr1 - arr2):", subtraction_result)

# 3. Multiplication (*)
multiplication_result = arr1 * arr2
print("Multiplication (arr1 * arr2):", multiplication_result)

# 4. Division (/)
division_result = arr1 / arr2
print("Division (arr1 / arr2):", division_result)

# 5. Exponentiation (**)
exponentiation_result = arr1 ** arr2
print("Exponentiation (arr1 ** arr2):", exponentiation_result)

# 6. Modulus (%)
modulus_result = arr1 % arr2
print("Modulus (arr1 % arr2):", modulus_result)

### Key Points:
- Each arithmetic operation is applied element-wise to `arr1` and `arr2`.
- The results are printed after performing each operation. You can modify the arrays or the operators to fit your needs.

## **Comparison Operators**

NumPy supports several comparison operators that work element-wise on arrays. These operators return boolean values (`True` or `False`) for each comparison.

### **List of Comparison Operators**:
- **`>`**: Greater than
- **`<`**: Less than
- **`>=`**: Greater than or equal to
- **`<=`**: Less than or equal to
- **`==`**: Equal to
- **`!=`**: Not equal to

### Explanation of Each Operator:

#### 1. **`>` (Greater than)**:
   - Compares if the left operand is **greater** than the right operand.
   - Returns `True` if the element on the left is greater than the element on the right, otherwise `False`.
   - **Example**: 
     ```python
     arr1 > arr2
     ```
     - Returns `True` where the corresponding element in `arr1` is greater than `arr2`.

#### 2. **`<` (Less than)**:
   - Compares if the left operand is **less** than the right operand.
   - Returns `True` if the element on the left is less than the element on the right, otherwise `False`.
   - **Example**: 
     ```python
     arr1 < arr2
     ```
     - Returns `True` where the corresponding element in `arr1` is less than `arr2`.

#### 3. **`>=` (Greater than or equal to)**:
   - Compares if the left operand is **greater than or equal to** the right operand.
   - Returns `True` if the element on the left is greater than or equal to the element on the right, otherwise `False`.
   - **Example**: 
     ```python
     arr1 >= arr2
     ```
     - Returns `True` where the corresponding element in `arr1` is greater than or equal to `arr2`.

#### 4. **`<=` (Less than or equal to)**:
   - Compares if the left operand is **less than or equal to** the right operand.
   - Returns `True` if the element on the left is less than or equal to the element on the right, otherwise `False`.
   - **Example**: 
     ```python
     arr1 <= arr2
     ```
     - Returns `True` where the corresponding element in `arr1` is less than or equal to `arr2`.

#### 5. **`==` (Equal to)**:
   - Compares if the left operand is **equal** to the right operand.
   - Returns `True` if the elements are equal, otherwise `False`.
   - **Example**: 
     ```python
     arr1 == arr2
     ```
     - Returns `True` where the corresponding elements in `arr1` and `arr2` are equal.

#### 6. **`!=` (Not equal to)**:
   - Compares if the left operand is **not equal** to the right operand.
   - Returns `True` if the elements are not equal, otherwise `False`.
   - **Example**: 
     ```python
     arr1 != arr2
     ```
     - Returns `True` where the corresponding elements in `arr1` and `arr2` are not equal.



Example:

In [ ]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 20, 25, 40, 45])

# Comparison operations
print("arr1 > arr2:", arr1 > arr2)  # Greater than
print("arr1 < arr2:", arr1 < arr2)  # Less than
print("arr1 >= arr2:", arr1 >= arr2)  # Greater than or equal to
print("arr1 <= arr2:", arr1 <= arr2)  # Less than or equal to
print("arr1 == arr2:", arr1 == arr2)  # Equal to
print("arr1 != arr2:", arr1 != arr2)  # Not equal to

## **Logical Operators**

NumPy supports several logical operators that work element-wise on arrays. These operators perform logical operations on boolean arrays or conditions, returning boolean values (`True` or `False`) for each comparison.

### **List of Logical Operators**:
- **`&`**: Logical AND
- **`|`**: Logical OR
- **`~`**: Logical NOT

### Explanation of Each Operator:

#### 1. **`&` (Logical AND)**:
   - Performs element-wise logical **AND** operation between two boolean arrays or conditions.
   - Returns `True` only if both corresponding elements are `True`; otherwise, it returns `False`.
   - **Example**: 
     ```python
     condition1 & condition2
     ```
     - Returns `True` where both conditions are `True` for each element.

#### 2. **`|` (Logical OR)**:
   - Performs element-wise logical **OR** operation between two boolean arrays or conditions.
   - Returns `True` if at least one of the corresponding elements is `True`; otherwise, it returns `False`.
   - **Example**: 
     ```python
     condition1 | condition2
     ```
     - Returns `True` where either `condition1` or `condition2` (or both) are `True`.

#### 3. **`~` (Logical NOT)**:
   - Performs element-wise logical **NOT** operation on a boolean array or condition.
   - Inverts the boolean values, changing `True` to `False` and vice versa.
   - **Example**: 
     ```python
     ~condition1
     ```
     - Returns `True` where `condition1` is `False`, and `False` where `condition1` is `True`.

---

Example:


In [ ]:
import numpy as np

# Create two NumPy arrays for logical conditions
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 20, 25, 40, 45])

# Create conditions based on the arrays
condition1 = arr1 > 20  # arr1 elements greater than 20
condition2 = arr2 < 40  # arr2 elements less than 40

# Logical operations
print("Logical AND (condition1 & condition2):", condition1 & condition2)  # AND
print("Logical OR (condition1 | condition2):", condition1 | condition2)   # OR
print("Logical NOT (~condition1):", ~condition1)  # NOT

---
## Common NumPy Functions

NumPy provides a huge library of functions for mathematical and statistical operations. Some commonly used ones include:

1. **Array Inspection**:
   - `arr.shape`: Get the dimensions of the array.
   - `arr.ndim`: Number of dimensions.
   - `arr.size`: Total number of elements.
   - `arr.dtype`: Data type of elements.


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # (2, 3)
print(arr.ndim)  # 2
print(arr.size)  # 6
print(arr.dtype) # int32

## **Mathematical Functions**

NumPy provides several functions to perform basic mathematical operations on arrays. These functions help calculate the sum, mean, median, standard deviation, minimum, maximum, and more.

### **List of Mathematical Functions**:
- **`np.sum(arr)`**: Sum of elements
- **`np.mean(arr)`**: Mean of elements
- **`np.median(arr)`**: Median of elements
- **`np.std(arr)`**: Standard deviation
- **`np.min(arr)`**, **`np.max(arr)`**: Minimum and maximum
- **`np.argmin(arr)`**, **`np.argmax(arr)`**: Indices of min and max

### Explanation of Each Function:

#### 1. **`np.sum(arr)`**:
   - Calculates the sum of all elements in the array `arr`.
   - **Example**: 
     ```python
     np.sum(arr)
     ```
     - Returns the total sum of the elements in the array.

#### 2. **`np.mean(arr)`**:
   - Calculates the mean (average) of all elements in the array `arr`.
   - **Example**: 
     ```python
     np.mean(arr)
     ```
     - Returns the average value of the elements in the array.

#### 3. **`np.median(arr)`**:
   - Calculates the median of the array `arr`, which is the middle value when the elements are sorted.
   - **Example**: 
     ```python
     np.median(arr)
     ```
     - Returns the median value.

#### 4. **`np.std(arr)`**:
   - Calculates the standard deviation of the elements in the array `arr`, which measures the spread of the numbers.
   - **Example**: 
     ```python
     np.std(arr)
     ```
     - Returns the standard deviation of the array.

#### 5. **`np.min(arr)`, `np.max(arr)`**:
   - Calculates the minimum and maximum values in the array `arr`.
   - **Example**:
     ```python
     np.min(arr), np.max(arr)
     ```
     - Returns the minimum and maximum values in the array.

#### 6. **`np.argmin(arr)`, `np.argmax(arr)`**:
   - Returns the indices of the minimum and maximum values in the array `arr`.
   - **Example**:
     ```python
     np.argmin(arr), np.argmax(arr)
     ```
     - Returns the indices of the minimum and maximum values.

Example:

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# 1. Sum of elements
sum_result = np.sum(arr)
print("Sum of elements:", sum_result)

# 2. Mean of elements
mean_result = np.mean(arr)
print("Mean of elements:", mean_result)

# 3. Median of elements
median_result = np.median(arr)
print("Median of elements:", median_result)

# 4. Standard deviation
std_result = np.std(arr)
print("Standard deviation:", std_result)

# 5. Minimum and maximum elements
min_result = np.min(arr)
max_result = np.max(arr)
print("Minimum element:", min_result)
print("Maximum element:", max_result)

# 6. Indices of min and max elements
argmin_result = np.argmin(arr)
argmax_result = np.argmax(arr)
print("Index of minimum element:", argmin_result)
print("Index of maximum element:", argmax_result)


3. **Reshaping and Transposing**:
- **`arr.reshape(new_shape)`**: Change the shape of the array without changing its data.
- **`arr.T`**: Transpose of a matrix (swap rows and columns).

### Explanation of Each Operation:

#### 1. **`arr.reshape(new_shape)`**:
   - This method allows you to change the shape of the array without changing the underlying data.
   - The total number of elements in the original array must match the total number of elements in the new shape.
   - **Example**:
     ```python
     arr.reshape(new_shape)
     ```
     - Converts the original array into the new shape (`new_shape`), preserving the original data order.
     - Example:
       ```python
       arr.reshape(2, 6)  # Reshape a 1D array with 12 elements into a 2D array of shape (2, 6)
       ```

#### 2. **`arr.T`**:
   - This method is used to compute the **transpose** of a matrix.
   - It swaps the rows and columns of the matrix (or swaps axes for higher-dimensional arrays).
   - **Example**:
     ```python
     arr.T
     ```
     - Transposes a 2D matrix, converting rows into columns and columns into rows.
     - Example:
       ```python
       arr.T  # For a 2D array, it swaps rows and columns
       ```

Example:


In [ ]:
import numpy as np

# Create a 1D array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Original Array
print("Original 1D Array:\n", arr, "\n")

# 1. Reshaping the array to a 2D array with shape (2, 6)
reshaped_arr = arr.reshape(2, 6)
print("Reshaped Array (2x6):\n", reshaped_arr)

# 2. Transposing the reshaped array (2x6 -> 6x2)
transposed_arr = reshaped_arr.T
print("\nTransposed Array (6x2):\n", transposed_arr)

4. **Sorting and Unique Values**:
   - `np.sort(arr)`: Returns a sorted copy of array.
   - `np.unique(arr)`: Finds unique elements of an array.

   Here’s a detailed explanation and example for **sorting** and **finding unique elements** in NumPy:

---

## **Sorting and Finding Unique Elements in Arrays**

NumPy provides built-in functions for sorting arrays and finding unique elements. These functions help in organizing data and identifying distinct values within an array.

### **List of Functions**:
- **`np.sort(arr)`**: Returns a sorted copy of the array.
- **`np.unique(arr)`**: Finds the unique elements of an array.

### Explanation of Each Function:

#### 1. **`np.sort(arr)`**:
   - This function returns a sorted copy of the array `arr`. The original array remains unchanged.
   - **Example**:
     ```python
     np.sort(arr)
     ```
     - Returns a new array with the elements sorted in ascending order.

#### 2. **`np.unique(arr)`**:
   - This function returns the unique elements of the array `arr`, eliminating duplicates.
   - **Example**:
     ```python
     np.unique(arr)
     ```
     - Returns an array of unique elements from the input array.

Example:


In [ ]:
import numpy as np

# Create an unsorted NumPy array
arr = np.array([10, 20, 10, 30, 40, 20, 50, 30])
print("Unsorted Array:", arr)

# 1. Sorting the array
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

# 2. Finding unique elements in the array
unique_elements = np.unique(arr)
print("Unique Elements:", unique_elements)

### **NumPy Indexing: A Comprehensive Guide**

Indexing is one of the most powerful and important features of **NumPy**. It allows you to access and manipulate individual elements or subsets of arrays efficiently. Let's explore different indexing techniques in **NumPy** with detailed explanations and examples.

---

### **1. Basic Indexing**

Basic indexing in NumPy is similar to Python's list indexing but with more capabilities. 

#### **1.1. Indexing a 1D Array**
In a 1D array, you access elements using a single index.

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
print(arr[0])  # Output: 10
print(arr[3])  # Output: 40

# Negative indexing (access elements from the end)
print(arr[-1])  # Output: 50 (last element)
print(arr[-2])  # Output: 40 (second last element)
```

#### **1.2. Indexing a 2D Array**
In a 2D array (matrix), you access elements using **two indices**: one for the row and one for the column.

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access element at row 0, column 2 (first row, third column)
print(arr_2d[0, 2])  # Output: 3

# Access element at row 2, column 1 (third row, second column)
print(arr_2d[2, 1])  # Output: 8

# Negative indexing
print(arr_2d[-1, -1])  # Output: 9 (last element of last row)
```

---

### **2. Slicing**

Slicing allows you to extract a **subarray** or **submatrix**. In NumPy, slicing works with a **start**, **stop**, and **step** syntax. The general syntax is:

```python
array[start:stop:step]
```

#### **2.1. Slicing a 1D Array**

```python
arr = np.array([10, 20, 30, 40, 50])

# Extract elements from index 1 to index 3 (exclusive)
print(arr[1:4])  # Output: [20 30 40]

# Slice from index 2 to the end
print(arr[2:])  # Output: [30 40 50]

# Slice from the beginning to index 3 (exclusive)
print(arr[:3])  # Output: [10 20 30]

# Slice with a step of 2 (every other element)
print(arr[::2])  # Output: [10 30 50]
```

#### **2.2. Slicing a 2D Array**

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the first two rows and first two columns
print(arr_2d[:2, :2])  
# Output:
# [[1 2]
#  [4 5]]

# Extract all rows, and columns from index 1 onwards
print(arr_2d[:, 1:])  
# Output:
# [[2 3]
#  [5 6]
#  [8 9]]

# Slice rows from index 1 onwards and every other column
print(arr_2d[1:, ::2])  
# Output:
# [[4 6]
#  [7 9]]
```

---

### **3. Fancy Indexing**

Fancy indexing, also known as **integer array indexing**, allows you to access multiple elements of an array at once using arrays of indices.

#### **3.1. Fancy Indexing in 1D Array**

```python
arr = np.array([10, 20, 30, 40, 50])

# Fancy indexing with a list of indices
print(arr[[0, 2, 4]])  # Output: [10 30 50]

# Fancy indexing with an array of indices
indices = np.array([1, 3])
print(arr[indices])  # Output: [20 40]
```

#### **3.2. Fancy Indexing in 2D Array**

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Fancy indexing with a list of row indices
print(arr_2d[[0, 2], :])  
# Output:
# [[1 2 3]
#  [7 8 9]]

# Fancy indexing with both row and column indices
rows = np.array([0, 1])
cols = np.array([1, 2])
print(arr_2d[rows, cols])  
# Output: [2 6]
```

---

### **4. Boolean Indexing**

Boolean indexing allows you to select elements from an array based on a **condition**.

#### **4.1. Boolean Indexing in 1D Array**

```python
arr = np.array([10, 20, 30, 40, 50])

# Select elements greater than 25
print(arr[arr > 25])  # Output: [30 40 50]
```

#### **4.2. Boolean Indexing in 2D Array**

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select elements greater than 5
print(arr_2d[arr_2d > 5])  
# Output: [6 7 8 9]

# Select rows where the first column is greater than 2
print(arr_2d[arr_2d[:, 0] > 2])  
# Output:
# [[3 4 5]
#  [6 7 8]]
```

---

### **5. Combining Indexing Techniques**

You can combine different indexing techniques like slicing, fancy indexing, and boolean indexing for more complex array manipulations.

#### **5.1. Combining Fancy and Boolean Indexing**

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use boolean indexing to select elements greater than 4, and fancy indexing to choose the first column
print(arr_2d[arr_2d > 4, 0])  
# Output: [7]
```

#### **5.2. Combining Slicing and Fancy Indexing**

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select rows 1 and 2, and columns 0 and 1
print(arr_2d[1:3, [0, 1]])  
# Output:
# [[4 5]
#  [7 8]]
```

---

### **6. Advanced Indexing: Ellipsis and Newaxis**

#### **6.1. Ellipsis (`...`)**

Ellipsis is used to represent multiple colons (`:`) in advanced indexing.

```python
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Select all elements in the first row and first column across all 2D arrays
print(arr_3d[..., 0])  
# Output:
# [[1 4]
#  [7 10]]
```

#### **6.2. Newaxis (`np.newaxis`)**

`np.newaxis` is used to increase the dimensions of an array by one more dimension.

```python
arr = np.array([1, 2, 3, 4])

# Convert 1D array to a 2D array (row vector)
row_vector = arr[np.newaxis, :]
print(row_vector)
# Output: [[1 2 3 4]]

# Convert 1D array to a 2D array (column vector)
column_vector = arr[:, np.newaxis]
print(column_vector)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]]
```

---

### **7. Multi-dimensional Indexing**

NumPy supports indexing for arrays with more than two dimensions. You can use multiple indices for selecting data from higher-dimensional arrays.

#### **7.1. Example with 3D Array**

```python
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Access a single element (first matrix, first row, second column)
print(arr_3d[0, 0, 1])  # Output: 2

# Select all values from the first matrix
print(arr_3d[0])  
# Output:
# [[1 2]
#  [3 4]]
```

---

### **Conclusion**

NumPy provides a wide range of **indexing capabilities** to manipulate and access elements in arrays. From simple **1D indexing** to advanced techniques like **fancy indexing**, **boolean indexing**, **slicing**, and **multi-dimensional indexing**, you can efficiently work with large datasets.

- **Basic indexing** allows you to access elements or slices of arrays.
- **Fancy indexing** allows for selecting specific elements using an array of indices.
- **Boolean indexing** lets you filter data based on conditions.
- **Multi-dimensional indexing** and **broadcasting** are powerful tools for working with higher-dimensional data.

Mastering these indexing techniques will help you handle data efficiently and manipulate arrays with ease in your data analysis, machine learning, or scientific computing tasks.



# Select all values from the first matrix
 


In [ ]:
print(arr_3d[0])

---

## Numpy for Data Analysis

NumPy is the backbone of data analysis in Python. While libraries like **Pandas** provide more convenient data structures for tabular data, NumPy is still central to:

1. **Handling Large Datasets**:  
   Efficient memory usage and fast computation let you handle large arrays of numerical data smoothly.

2. **Vectorized Computations**:  
   Apply mathematical transformations to entire datasets without writing explicit loops.

3. **Integration with Other Libraries**:  
   NumPy arrays form the raw data structure for Pandas `DataFrame`, Matplotlib plots, and SciPy scientific functions.

### Example: Basic Data Analysis Steps Using NumPy

Suppose you have a dataset representing the heights of individuals in centimeters:

In [ ]:
import numpy as np

heights = np.array([170, 165, 180, 175, 160, 182, 178, 155, 188, 172])

# 1. Basic Statistics
mean_height = np.mean(heights)
median_height = np.median(heights)
std_height = np.std(heights)

print("Mean height:", mean_height)
print("Median height:", median_height)
print("Standard Deviation:", std_height)

print()

# 2. Filtering Data
# Find all individuals taller than 175 cm
tall_people = heights[heights > 175]
print("Heights of tall individuals:", tall_people)

print()

# 3. Combining & Reshaping
# Suppose we have another array representing weights
weights = np.array([68, 63, 85, 77, 58, 80, 75, 55, 90, 70])

# Create a 2D array of shape (10,2) where first column is height and second column is weight
data = np.column_stack((heights, weights))
print("Combined data (height, weight):\n", data)

print()

# Compute the correlation between heights and weights
correlation_matrix = np.corrcoef(heights, weights)
print("Correlation between heights and weights:\n", correlation_matrix)

## **Advanced NumPy Operations**

### **Reshaping Arrays**
You can reshape arrays for different dimensionalities.

**Reshape**:


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
# Output: 
# [[1 2 3]
#  [4 5 6]]

**Flatten**:

In [ ]:
flattened = reshaped.flatten()
print(flattened)  # [1, 2, 3, 4, 5, 6]


### **Broadcasting in NumPy**
Broadcasting is a powerful feature that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the dimensions of arrays to make them compatible.

**Example**:


In [ ]:
arr = np.array([1, 2, 3])
result = arr + 10  # Adds 10 to each element in the array
print(result)  # [11, 12, 13]


---

## **Statistical Functions**

### **Descriptive Statistics**
NumPy makes it easy to compute various statistical metrics like mean, median, standard deviation, etc.

**Mean**:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0


**Median**:


In [ ]:
print(np.median(arr))  # Output: 3.0

**Standard Deviation**:


In [ ]:
print(np.std(arr))  # Output: 1.4142135623730951

**Variance**:


In [ ]:
print(np.var(arr))  # Output: 2.0

**Min and Max**:


In [ ]:
print(np.min(arr))  # Output: 1
print(np.max(arr))  # Output: 5

```python

```

---

## **Matrix Operations**

### **Dot Product**
The dot product of two arrays can be computed using `np.dot()` or the `@` operator for matrices.


In [ ]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

dot_product = np.dot(arr1, arr2)
print(dot_product)  # Output: 11 (1*3 + 2*4)

# Or using the @ operator
dot_product = arr1 @ arr2
print(dot_product)  # Output: 11


### **Matrix Multiplication**
You can multiply matrices using `np.dot()` or the `@` operator.


In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
print(result)


### **Determinant and Inverse of a Matrix**
NumPy provides functions to calculate the determinant and the inverse of a matrix.


In [ ]:
matrix = np.array([[1, 2], [3, 4]])

det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)

print("Determinant:", det)
print("Inverse:\n", inv)


---

## **Array Manipulation**

### **Stacking Arrays**
You can stack arrays along different axes using functions like `np.vstack()`, `np.hstack()`, or `np.dstack()`.


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stacking (row-wise)
vstacked = np.vstack((arr1, arr2))
print(vstacked)

# Horizontal stacking (column-wise)
hstacked = np.hstack((arr1, arr2))
print(hstacked)


### **Splitting Arrays**
You can split an array into multiple sub-arrays using `np.split()`.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 2 sub-arrays
splits = np.split(arr, 2)
print(splits)  # [array([1, 2, 3]), array([4, 5, 6])]

## **Code for Random Dataset and Data Analysis using NumPy**:

In [ ]:
import numpy as np

# 1. Generate Random Dataset for Heights and Weights
np.random.seed(42)  # Set seed for reproducibility

# Generate random heights between 150 cm and 190 cm (inclusive)
heights = np.random.randint(150, 191, size=1000)

# Generate random weights between 45 kg and 100 kg (inclusive)
weights = np.random.randint(45, 101, size=1000)

# 2. Basic Analysis
# Compute the mean, median, and standard deviation for heights and weights
mean_height = np.mean(heights)
mean_weight = np.mean(weights)
median_height = np.median(heights)
median_weight = np.median(weights)
std_height = np.std(heights)
std_weight = np.std(weights)

print("Basic Statistics:")
print(f"Mean Height: {mean_height} cm")
print(f"Mean Weight: {mean_weight} kg")
print(f"Median Height: {median_height} cm")
print(f"Median Weight: {median_weight} kg")
print(f"Standard Deviation of Heights: {std_height} cm")
print(f"Standard Deviation of Weights: {std_weight} kg")

# 3. Unique Values (to check range of heights and weights)
unique_heights = np.unique(heights)
unique_weights = np.unique(weights)
print("\nUnique Values:")
print(f"Number of Unique Heights: {len(unique_heights)}")
print(f"Number of Unique Weights: {len(unique_weights)}")

# 4. Correlation Between Heights and Weights
correlation = np.corrcoef(heights, weights)[0, 1]
print("\nCorrelation Between Heights and Weights:", correlation)

# 5. Filtering Data
# Find all individuals with height above 180 cm
tall_people = heights[heights > 180]
print(f"\nNumber of people taller than 180 cm: {len(tall_people)}")

# 6. Further Analysis (Average Weight for People Above 180 cm)
avg_weight_tall_people = np.mean(weights[heights > 180])
print(f"\nAverage weight of people taller than 180 cm: {avg_weight_tall_people:.2f} kg")

# 7. Creating a 2D Dataset and Displaying Specific Data
# Combine heights and weights into a 2D array
dataset = np.column_stack((heights, weights))

# Display first 10 rows of the dataset
print("\nFirst 10 rows of the dataset (height, weight):")
print(dataset[:10])

# Access a specific column (heights or weights)
print("\nFirst 10 heights:")
print(dataset[:10, 0])  # Accessing the height column

# 8. Sorting the Data Based on Heights
sorted_indices = np.argsort(heights)  # Get indices that would sort the heights
sorted_heights = heights[sorted_indices]
sorted_weights = weights[sorted_indices]

print("\nSorted Heights (Ascending):")
print(sorted_heights[:10])  # Display first 10 sorted heights

# 9. Maximum and Minimum of Heights and Weights
max_height = np.max(heights)
min_height = np.min(heights)
max_weight = np.max(weights)
min_weight = np.min(weights)

print("\nMaximum and Minimum Values:")
print(f"Maximum Height: {max_height} cm")
print(f"Minimum Height: {min_height} cm")
print(f"Maximum Weight: {max_weight} kg")
print(f"Minimum Weight: {min_weight} kg")


### **Explanation of Code**:

1. **Generate Random Data**:
   - Heights and weights are generated using `np.random.randint()` to simulate random values for these attributes. Heights are between 150 cm and 190 cm, and weights are between 45 kg and 100 kg.

2. **Basic Analysis**:
   - **Mean, Median, and Standard Deviation** are calculated for both **heights** and **weights** using `np.mean()`, `np.median()`, and `np.std()` respectively.

3. **Unique Values**:
   - The unique values in the `heights` and `weights` arrays are found using `np.unique()`, which helps determine the range of values in the dataset.

4. **Correlation**:
   - The correlation between **heights** and **weights** is computed using `np.corrcoef()`, which returns the correlation matrix. The value at `[0, 1]` gives the correlation coefficient.

5. **Filtering Data**:
   - The code filters the dataset to find all individuals taller than **180 cm** using boolean indexing. This allows you to perform operations like extracting specific subsets of the data.

6. **Further Analysis**:
   - The **average weight** of people taller than 180 cm is computed using `np.mean()` on the filtered weights.

7. **Creating and Accessing a 2D Dataset**:
   - Heights and weights are combined into a 2D array (`dataset`) using `np.column_stack()`. The first 10 rows are displayed.
   - Specific columns (heights and weights) are accessed by indexing.

8. **Sorting**:
   - The dataset is sorted based on the **heights** using `np.argsort()`, which returns the indices that would sort the array. The sorted values are then displayed.

9. **Maximum and Minimum**:
   - The **maximum** and **minimum** heights and weights are computed using `np.max()` and `np.min()`.